#!/usr/bin/env bash
# A script that installs nginx server on an ubuntu 
# The installed server should listen to post 80 for connection
# and servers a default page index.html

sudo apt-get update -y

sudo apt-get install nginx -y
ufw allow 'Nginx HTTP'

echo 'Hello World!' > /var/www/html/index.html

service nginx start
