#!/bin/bash
# Pings an IP address received as an argument 5 times.
# Check if no argument is passed
if [ "$#" -ne 1 ]; then
    echo "Usage: $(basename "$0") {IP_ADDRESS}"
    exit 1
fi

# Assign the argument to a variable
ip_address="$1"

# Ping the IP address 5 times
ping -c 5 "$ip_address"
