#!/usr/bin/env bash
# Script displays "Best School" 10 times using while loop.
# on the 9th iteration, displays "hi" before "Best School".

count=0

while [ $count -lt 10 ]
do
	if [ $count -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( count++ ))
done
